// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Static-import registry of every action file. Bundlers (Nitro, Rolldown)
// see these imports and include the action modules in the server bundle.
// The agent-chat plugin normalizes each module into an ActionEntry shape.
import * as a_book_meeting_calendar from "../actions/book-meeting-calendar";
import * as a_bootstrap_admin from "../actions/bootstrap-admin";
import * as a_confirm_workflow from "../actions/confirm-workflow";
import * as a_delete_meeting from "../actions/delete-meeting";
import * as a_disconnect_google_calendar from "../actions/disconnect-google-calendar";
import * as a_disconnect_nooks from "../actions/disconnect-nooks";
import * as a_disconnect_zoom from "../actions/disconnect-zoom";
import * as a_get_calendar_events from "../actions/get-calendar-events";
import * as a_get_current_user from "../actions/get-current-user";
import * as a_get_meeting_detail from "../actions/get-meeting-detail";
import * as a_get_user_names from "../actions/get-user-names";
import * as a_hello from "../actions/hello";
import * as a_initiate_workflow from "../actions/initiate-workflow";
import * as a_list_meetings from "../actions/list-meetings";
import * as a_list_users from "../actions/list-users";
import * as a_navigate from "../actions/navigate";
import * as a_set_user_role from "../actions/set-user-role";
import * as a_update_meeting from "../actions/update-meeting";
import * as a_view_screen from "../actions/view-screen";
import * as a_get_feature_flags from "@agent-native/core/feature-flags/actions/get-feature-flags";
import * as a_list_feature_flags from "@agent-native/core/feature-flags/actions/list-feature-flags";
import * as a_set_feature_flag from "@agent-native/core/feature-flags/actions/set-feature-flag";
import * as a_share_resource from "@agent-native/core/sharing/actions/share-resource";
import * as a_unshare_resource from "@agent-native/core/sharing/actions/unshare-resource";
import * as a_list_resource_shares from "@agent-native/core/sharing/actions/list-resource-shares";
import * as a_set_resource_visibility from "@agent-native/core/sharing/actions/set-resource-visibility";
import * as a_upload_image from "@agent-native/core/file-upload/actions/upload-image";
import * as a_context_manifest_get from "@agent-native/core/agent/context-xray/actions/context-manifest-get";
import * as a_context_pin from "@agent-native/core/agent/context-xray/actions/context-pin";
import * as a_context_evict from "@agent-native/core/agent/context-xray/actions/context-evict";
import * as a_context_restore from "@agent-native/core/agent/context-xray/actions/context-restore";
import * as a_context_report from "@agent-native/core/agent/context-xray/actions/context-report";
import * as a_get_localization_preference from "@agent-native/core/localization/actions/get-localization-preference";
import * as a_set_localization_preference from "@agent-native/core/localization/actions/set-localization-preference";
import * as a_create_resource_version from "@agent-native/core/history/actions/create-resource-version";
import * as a_list_resource_versions from "@agent-native/core/history/actions/list-resource-versions";
import * as a_get_resource_version from "@agent-native/core/history/actions/get-resource-version";
import * as a_restore_resource_version from "@agent-native/core/history/actions/restore-resource-version";
import * as a_list_resource_history from "@agent-native/core/history/actions/list-resource-history";
import * as a_list_review_comments from "@agent-native/core/review/actions/list-review-comments";
import * as a_create_review_comment from "@agent-native/core/review/actions/create-review-comment";
import * as a_reply_review_comment from "@agent-native/core/review/actions/reply-review-comment";
import * as a_resolve_review_thread from "@agent-native/core/review/actions/resolve-review-thread";
import * as a_delete_review_comment from "@agent-native/core/review/actions/delete-review-comment";
import * as a_consume_review_feedback from "@agent-native/core/review/actions/consume-review-feedback";
import * as a_get_review_feedback from "@agent-native/core/review/actions/get-review-feedback";
import * as a_set_review_status from "@agent-native/core/review/actions/set-review-status";
import * as a_send_review_thread_to_agent from "@agent-native/core/review/actions/send-review-thread-to-agent";

const modules: Record<string, unknown> = {
  "book-meeting-calendar": a_book_meeting_calendar,
  "bootstrap-admin": a_bootstrap_admin,
  "confirm-workflow": a_confirm_workflow,
  "delete-meeting": a_delete_meeting,
  "disconnect-google-calendar": a_disconnect_google_calendar,
  "disconnect-nooks": a_disconnect_nooks,
  "disconnect-zoom": a_disconnect_zoom,
  "get-calendar-events": a_get_calendar_events,
  "get-current-user": a_get_current_user,
  "get-meeting-detail": a_get_meeting_detail,
  "get-user-names": a_get_user_names,
  "hello": a_hello,
  "initiate-workflow": a_initiate_workflow,
  "list-meetings": a_list_meetings,
  "list-users": a_list_users,
  "navigate": a_navigate,
  "set-user-role": a_set_user_role,
  "update-meeting": a_update_meeting,
  "view-screen": a_view_screen,
  "get-feature-flags": a_get_feature_flags,
  "list-feature-flags": a_list_feature_flags,
  "set-feature-flag": a_set_feature_flag,
  "share-resource": a_share_resource,
  "unshare-resource": a_unshare_resource,
  "list-resource-shares": a_list_resource_shares,
  "set-resource-visibility": a_set_resource_visibility,
  "upload-image": a_upload_image,
  "context-manifest-get": a_context_manifest_get,
  "context-pin": a_context_pin,
  "context-evict": a_context_evict,
  "context-restore": a_context_restore,
  "context-report": a_context_report,
  "get-localization-preference": a_get_localization_preference,
  "set-localization-preference": a_set_localization_preference,
  "create-resource-version": a_create_resource_version,
  "list-resource-versions": a_list_resource_versions,
  "get-resource-version": a_get_resource_version,
  "restore-resource-version": a_restore_resource_version,
  "list-resource-history": a_list_resource_history,
  "list-review-comments": a_list_review_comments,
  "create-review-comment": a_create_review_comment,
  "reply-review-comment": a_reply_review_comment,
  "resolve-review-thread": a_resolve_review_thread,
  "delete-review-comment": a_delete_review_comment,
  "consume-review-feedback": a_consume_review_feedback,
  "get-review-feedback": a_get_review_feedback,
  "set-review-status": a_set_review_status,
  "send-review-thread-to-agent": a_send_review_thread_to_agent,
};

export default modules;
