// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare global {
  interface AgentNativeActionRegistry {
    "book-meeting-calendar": ActionEntry<typeof import("../actions/book-meeting-calendar")>;
    "bootstrap-admin": ActionEntry<typeof import("../actions/bootstrap-admin")>;
    "confirm-workflow": ActionEntry<typeof import("../actions/confirm-workflow")>;
    "delete-meeting": ActionEntry<typeof import("../actions/delete-meeting")>;
    "disconnect-google-calendar": ActionEntry<typeof import("../actions/disconnect-google-calendar")>;
    "disconnect-nooks": ActionEntry<typeof import("../actions/disconnect-nooks")>;
    "disconnect-zoom": ActionEntry<typeof import("../actions/disconnect-zoom")>;
    "get-calendar-events": ActionEntry<typeof import("../actions/get-calendar-events")>;
    "get-current-user": ActionEntry<typeof import("../actions/get-current-user")>;
    "get-meeting-detail": ActionEntry<typeof import("../actions/get-meeting-detail")>;
    "get-user-names": ActionEntry<typeof import("../actions/get-user-names")>;
    "hello": ActionEntry<typeof import("../actions/hello")>;
    "initiate-workflow": ActionEntry<typeof import("../actions/initiate-workflow")>;
    "list-meetings": ActionEntry<typeof import("../actions/list-meetings")>;
    "list-users": ActionEntry<typeof import("../actions/list-users")>;
    "navigate": ActionEntry<typeof import("../actions/navigate")>;
    "set-user-role": ActionEntry<typeof import("../actions/set-user-role")>;
    "update-meeting": ActionEntry<typeof import("../actions/update-meeting")>;
    "view-screen": ActionEntry<typeof import("../actions/view-screen")>;
    "get-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/get-feature-flags")>;
    "list-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/list-feature-flags")>;
    "set-feature-flag": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/set-feature-flag")>;
    "share-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/share-resource")>;
    "unshare-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/unshare-resource")>;
    "list-resource-shares": ActionEntry<typeof import("@agent-native/core/sharing/actions/list-resource-shares")>;
    "set-resource-visibility": ActionEntry<typeof import("@agent-native/core/sharing/actions/set-resource-visibility")>;
    "upload-image": ActionEntry<typeof import("@agent-native/core/file-upload/actions/upload-image")>;
    "context-manifest-get": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-manifest-get")>;
    "context-pin": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-pin")>;
    "context-evict": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-evict")>;
    "context-restore": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-restore")>;
    "context-report": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-report")>;
    "get-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/get-localization-preference")>;
    "set-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/set-localization-preference")>;
    "create-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/create-resource-version")>;
    "list-resource-versions": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-versions")>;
    "get-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/get-resource-version")>;
    "restore-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/restore-resource-version")>;
    "list-resource-history": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-history")>;
    "list-review-comments": ActionEntry<typeof import("@agent-native/core/review/actions/list-review-comments")>;
    "create-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/create-review-comment")>;
    "reply-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/reply-review-comment")>;
    "resolve-review-thread": ActionEntry<typeof import("@agent-native/core/review/actions/resolve-review-thread")>;
    "delete-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/delete-review-comment")>;
    "consume-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/consume-review-feedback")>;
    "get-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/get-review-feedback")>;
    "set-review-status": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-status")>;
    "send-review-thread-to-agent": ActionEntry<typeof import("@agent-native/core/review/actions/send-review-thread-to-agent")>;
  }
}

declare module "@agent-native/core/client" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

declare module "@agent-native/core/client/hooks" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

export {};
