// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat/:threadId": {
    params: {
      "threadId": string;
    };
  };
  "/observability": {
    params: {};
  };
  "/extensions": {
    params: {};
  };
  "/extensions/:id": {
    params: {
      "id": string;
    };
  };
  "/extensions/:id/:slug": {
    params: {
      "id": string;
      "slug": string;
    };
  };
  "/database": {
    params: {};
  };
  "/meetings": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/workflow": {
    params: {};
  };
  "/pending": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/agent": {
    params: {};
  };
  "/team": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat/:threadId" | "/observability" | "/extensions" | "/extensions/:id" | "/extensions/:id/:slug" | "/database" | "/meetings" | "/settings" | "/workflow" | "/pending" | "/admin" | "/agent" | "/team";
  };
  "routes/chat.$threadId.tsx": {
    id: "routes/chat.$threadId";
    page: "/chat/:threadId";
  };
  "routes/observability.tsx": {
    id: "routes/observability";
    page: "/observability";
  };
  "routes/extensions.tsx": {
    id: "routes/extensions";
    page: "/extensions" | "/extensions/:id" | "/extensions/:id/:slug";
  };
  "routes/extensions._index.tsx": {
    id: "routes/extensions._index";
    page: "/extensions";
  };
  "routes/extensions.$id.tsx": {
    id: "routes/extensions.$id";
    page: "/extensions/:id" | "/extensions/:id/:slug";
  };
  "routes/extensions.$id.$slug.tsx": {
    id: "routes/extensions.$id.$slug";
    page: "/extensions/:id/:slug";
  };
  "routes/database.tsx": {
    id: "routes/database";
    page: "/database";
  };
  "routes/meetings.tsx": {
    id: "routes/meetings";
    page: "/meetings";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/workflow.tsx": {
    id: "routes/workflow";
    page: "/workflow";
  };
  "routes/pending.tsx": {
    id: "routes/pending";
    page: "/pending";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/agent.tsx": {
    id: "routes/agent";
    page: "/agent";
  };
  "routes/team.tsx": {
    id: "routes/team";
    page: "/team";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/chat.$threadId": typeof import("./app/routes/chat.$threadId.tsx");
  "routes/observability": typeof import("./app/routes/observability.tsx");
  "routes/extensions": typeof import("./app/routes/extensions.tsx");
  "routes/extensions._index": typeof import("./app/routes/extensions._index.tsx");
  "routes/extensions.$id": typeof import("./app/routes/extensions.$id.tsx");
  "routes/extensions.$id.$slug": typeof import("./app/routes/extensions.$id.$slug.tsx");
  "routes/database": typeof import("./app/routes/database.tsx");
  "routes/meetings": typeof import("./app/routes/meetings.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/workflow": typeof import("./app/routes/workflow.tsx");
  "routes/pending": typeof import("./app/routes/pending.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/agent": typeof import("./app/routes/agent.tsx");
  "routes/team": typeof import("./app/routes/team.tsx");
};